### ISSUE TITLE
GUI Permissions vs Commands

### ISSUE THREAD

**Issue by Tanjitsu** [Loving11ish/PlayerGUIAdvanced#1]
usage: /actions <player>
permission: playergui.mod

The Action requires a permission 
but.... if i enter the GUI using /players then click on a player (it enters the mod screen but does not check the perm).

It would be nice if it carried out the same check, this way /players can be used by people who dont have access to spectate / tp / mod.

**Comment by Loving11ish** [comment]
Ah I see your problem, thanks for bringing this to my attention.  I will ads this to next release.
