### ISSUE TITLE
Minor Spelling

### ISSUE THREAD

**Issue by Tanjitsu** [Loving11ish/PlayerGUIAdvanced#2]
https://github.com/Loving11ish/PlayerGUIAdvanced/blob/91f7dfb419841d14c25425ec7c8d40994f624202/src/main/resources/config.yml#L412

I noticed the above when reading the config.
Should?  Ban-manager-nemu-title 
Be  Ban-manager-menu-title

**Comment by Loving11ish** [comment]
Ah yes, good spot.  I will correct this in the next release.

**Comment by Loving11ish** [comment]
All fixed
